### ISSUE TITLE
Copy ssh keys from host

### ISSUE THREAD

**Issue by danny-cheung** [siso/chef-takeaway#21]
```
config.vm.provision "file", source: "#{Dir.home}/.ssh/config", destination: ".ssh/config"
```

copies ~/.ssh/config to the guest VM.

Should copy across id_rsa and id_rsa.pub as well.

**Comment by siso** [comment]
Please, see [Quickstart](https://github.com/siso/chef-takeaway#quickstart), if `-A`SSH option is used:

``` sh
vagrant ssh -- -A
```

then forwarding of the authentication agent connection is enabled, and public/private SSH keys do not need to be copied on the guest box.
